name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create config.js
      run: |
        echo "window.config = {" > config.js
        echo "  API_URL: '${{ secrets.API_URL }}'," >> config.js
        echo "  SPREADSHEET_URL: '${{ secrets.SPREADSHEET_URL }}'" >> config.js
        echo "};" >> config.js
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .